# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acbd0f79c35abcea949ddf0bc5fccba2df6523951f4ced3c51f2150ba1d8209166713cff54d23beb9ecd2556cf85ee743fee50bbcccd886fc4fb7daac7dc89c9

test:
  secret_key_base: d5a53d3727511fa2afb8343cd0152d37147312bbf02d5b5193acd53b91189ff380672d1282a9976accf20b45746912d831a731362c37e7ddd51bb2d0064de7b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
